#!/bin/sh
# --------------------------------------------------------------------------
# OpenPanel - The Open Source Control Panel
# Copyright (c) 2006-2007 PanelSix
#
# This software and its source code are subject to version 2 of the
# GNU General Public License. Please be aware that use of the OpenPanel
# and PanelSix trademarks and the IconBase.com iconset may be subject
# to additional restrictions. For more information on these restrictions
# and for a copy of version 2 of the GNU General Public License, please
# visit the Legal and Privacy Information section of the OpenPanel
# website on http:#www.openpanel.com/
# --------------------------------------------------------------------------
if [ -d /etc/httpd ]; then
  if [ ! -d /etc/httpd/openpanel.d ]; then
    echo "No /etc/httpd/openpanel.d"
    echo "quit" >&3
    exit 1
  fi
  if [ ! -f /etc/httpd/conf.d/openpanel.conf ]; then
    echo "File openpanel.conf not found in etc/httpd/conf.d"
    echo "quit" >&3
    exit 1
  fi
else
  if [ ! -d /etc/apache2 ]; then
    echo "Apache not found"
    echo "quit" >&3
    exit 1
  fi
  if [ ! -f /etc/apache2/conf.d/openpanel.conf ]; then
    echo "Openpanel.d not included in config"
    echo "quit" >&3
    exit 1
  fi
fi
